version: 2

updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Prague"
    open-pull-requests-limit: 1
    groups:
      nuget-updates:
        patterns:
          - "*"

  - package-ecosystem: "dotnet-sdk"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:15"
      timezone: "Europe/Prague"
    open-pull-requests-limit: 1

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:30"
      timezone: "Europe/Prague"
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - "*"
