// <auto-generated />
using System;
using FuaPay.Web.BuildingBlocks.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FuaPay.Web.BuildingBlocks.Persistence.Migrations
{
    [DbContext(typeof(FuaPayDbContext))]
    [Migration("20260725170405_InitialCreditsSchema")]
    partial class InitialCreditsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FuaPay.Web.Modules.Credits.Infrastructure.Persistence.CreditAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("BalanceMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_minor_units");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_credits_accounts");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasDatabaseName("uq_credits_accounts_owner");

                    b.ToTable("accounts", "credits", t =>
                        {
                            t.HasCheckConstraint("ck_credits_accounts_balance_non_negative", "balance_minor_units >= 0");

                            t.HasCheckConstraint("ck_credits_accounts_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_credits_accounts_owner_not_empty", "owner_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_credits_accounts_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Credits.Infrastructure.Persistence.CreditMovementEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<long>("AmountMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor_units");

                    b.Property<long>("BalanceAfterMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after_minor_units");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer")
                        .HasColumnName("movement_type");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("pk_credits_movements");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("uq_credits_movements_operation");

                    b.HasIndex("AccountId", "RecordedAt")
                        .HasDatabaseName("ix_credits_movements_account_recorded_at");

                    b.HasIndex("AccountId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("uq_credits_movements_account_sequence");

                    b.ToTable("movements", "credits", t =>
                        {
                            t.HasCheckConstraint("ck_credits_movements_account_not_empty", "account_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_credits_movements_amount_positive", "amount_minor_units > 0");

                            t.HasCheckConstraint("ck_credits_movements_balance_non_negative", "balance_after_minor_units >= 0");

                            t.HasCheckConstraint("ck_credits_movements_description_not_empty", "length(btrim(description)) > 0");

                            t.HasCheckConstraint("ck_credits_movements_operation_not_empty", "operation_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_credits_movements_sequence_positive", "sequence > 0");

                            t.HasCheckConstraint("ck_credits_movements_type_valid", "movement_type IN (1, 2)");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Credits.Infrastructure.Persistence.CreditMovementEntity", b =>
                {
                    b.HasOne("FuaPay.Web.Modules.Credits.Infrastructure.Persistence.CreditAccountEntity", "Account")
                        .WithMany("Movements")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Credits.Infrastructure.Persistence.CreditAccountEntity", b =>
                {
                    b.Navigation("Movements");
                });
#pragma warning restore 612, 618
        }
    }
}
