// <auto-generated />
using System;
using FuaPay.Web.BuildingBlocks.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FuaPay.Web.BuildingBlocks.Persistence.Migrations
{
    [DbContext(typeof(FuaPayDbContext))]
    [Migration("20260726115746_AddAccessSchema")]
    partial class AddAccessSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FuaPay.Web.Modules.Access.Infrastructure.Persistence.AccessUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_access_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_access_users_email");

                    b.ToTable("users", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_users_display_name_not_empty", "length(btrim(display_name)) > 0");

                            t.HasCheckConstraint("ck_access_users_email_not_empty", "email IS NULL OR length(btrim(email)) > 0");

                            t.HasCheckConstraint("ck_access_users_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_access_users_last_seen_valid", "last_seen_at >= created_at");

                            t.HasCheckConstraint("ck_access_users_status_valid", "status IN (1, 2)");

                            t.HasCheckConstraint("ck_access_users_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Access.Infrastructure.Persistence.ExternalIdentityEntity", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("Tenant")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Provider", "Tenant", "Subject")
                        .HasName("pk_access_external_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_access_external_identities_user");

                    b.ToTable("external_identities", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_external_identities_provider_not_empty", "length(btrim(provider)) > 0");

                            t.HasCheckConstraint("ck_access_external_identities_subject_not_empty", "length(btrim(subject)) > 0");

                            t.HasCheckConstraint("ck_access_external_identities_tenant_not_empty", "length(btrim(tenant)) > 0");

                            t.HasCheckConstraint("ck_access_external_identities_user_not_empty", "user_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Access.Infrastructure.Persistence.RoleAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedByProcessName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("granted_by_process_name");

                    b.Property<int>("GrantedByType")
                        .HasColumnType("integer")
                        .HasColumnName("granted_by_type");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByProcessName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("revoked_by_process_name");

                    b.Property<int?>("RevokedByType")
                        .HasColumnType("integer")
                        .HasColumnName("revoked_by_type");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_access_role_assignments");

                    b.HasIndex("GrantedByUserId")
                        .HasDatabaseName("ix_access_role_assignments_granted_by_user");

                    b.HasIndex("RevokedByUserId")
                        .HasDatabaseName("ix_access_role_assignments_revoked_by_user");

                    b.HasIndex("UserId", "GrantedAt")
                        .HasDatabaseName("ix_access_role_assignments_user_granted_at");

                    b.HasIndex("UserId", "Role")
                        .IsUnique()
                        .HasDatabaseName("uq_access_role_assignments_active_role")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("role_assignments", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_role_assignments_granted_actor_valid", "(\n    granted_by_type = 1\n    AND granted_by_user_id IS NOT NULL\n    AND granted_by_process_name IS NULL\n)\nOR\n(\n    granted_by_type = 2\n    AND granted_by_user_id IS NULL\n    AND granted_by_process_name IS NOT NULL\n    AND length(btrim(granted_by_process_name)) > 0\n)");

                            t.HasCheckConstraint("ck_access_role_assignments_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_access_role_assignments_revoked_actor_valid", "(\n    revoked_at IS NULL\n    AND revoked_by_type IS NULL\n    AND revoked_by_user_id IS NULL\n    AND revoked_by_process_name IS NULL\n)\nOR\n(\n    revoked_at IS NOT NULL\n    AND revoked_at >= granted_at\n    AND\n    (\n        (\n            revoked_by_type = 1\n            AND revoked_by_user_id IS NOT NULL\n            AND revoked_by_process_name IS NULL\n        )\n        OR\n        (\n            revoked_by_type = 2\n            AND revoked_by_user_id IS NULL\n            AND revoked_by_process_name IS NOT NULL\n            AND length(btrim(revoked_by_process_name)) > 0\n        )\n    )\n)");

                            t.HasCheckConstraint("ck_access_role_assignments_role_valid", "role IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_access_role_assignments_user_not_empty", "user_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Credits.Infrastructure.Persistence.CreditAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("BalanceMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_minor_units");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_credits_accounts");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasDatabaseName("uq_credits_accounts_owner");

                    b.ToTable("accounts", "credits", t =>
                        {
                            t.HasCheckConstraint("ck_credits_accounts_balance_non_negative", "balance_minor_units >= 0");

                            t.HasCheckConstraint("ck_credits_accounts_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_credits_accounts_owner_not_empty", "owner_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_credits_accounts_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Credits.Infrastructure.Persistence.CreditMovementEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<long>("AmountMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor_units");

                    b.Property<long>("BalanceAfterMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after_minor_units");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer")
                        .HasColumnName("movement_type");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("pk_credits_movements");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("uq_credits_movements_operation");

                    b.HasIndex("AccountId", "RecordedAt")
                        .HasDatabaseName("ix_credits_movements_account_recorded_at");

                    b.HasIndex("AccountId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("uq_credits_movements_account_sequence");

                    b.ToTable("movements", "credits", t =>
                        {
                            t.HasCheckConstraint("ck_credits_movements_account_not_empty", "account_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_credits_movements_amount_positive", "amount_minor_units > 0");

                            t.HasCheckConstraint("ck_credits_movements_balance_non_negative", "balance_after_minor_units >= 0");

                            t.HasCheckConstraint("ck_credits_movements_description_not_empty", "length(btrim(description)) > 0");

                            t.HasCheckConstraint("ck_credits_movements_operation_not_empty", "operation_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_credits_movements_sequence_positive", "sequence > 0");

                            t.HasCheckConstraint("ck_credits_movements_type_valid", "movement_type IN (1, 2)");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Access.Infrastructure.Persistence.ExternalIdentityEntity", b =>
                {
                    b.HasOne("FuaPay.Web.Modules.Access.Infrastructure.Persistence.AccessUserEntity", "User")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_external_identities_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Access.Infrastructure.Persistence.RoleAssignmentEntity", b =>
                {
                    b.HasOne("FuaPay.Web.Modules.Access.Infrastructure.Persistence.AccessUserEntity", null)
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_access_role_assignments_granted_by_user");

                    b.HasOne("FuaPay.Web.Modules.Access.Infrastructure.Persistence.AccessUserEntity", null)
                        .WithMany()
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_access_role_assignments_revoked_by_user");

                    b.HasOne("FuaPay.Web.Modules.Access.Infrastructure.Persistence.AccessUserEntity", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_role_assignments_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Credits.Infrastructure.Persistence.CreditMovementEntity", b =>
                {
                    b.HasOne("FuaPay.Web.Modules.Credits.Infrastructure.Persistence.CreditAccountEntity", "Account")
                        .WithMany("Movements")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Access.Infrastructure.Persistence.AccessUserEntity", b =>
                {
                    b.Navigation("ExternalIdentities");

                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Credits.Infrastructure.Persistence.CreditAccountEntity", b =>
                {
                    b.Navigation("Movements");
                });
#pragma warning restore 612, 618
        }
    }
}
