// <auto-generated />
using System;
using FuaPay.Web.BuildingBlocks.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FuaPay.Web.BuildingBlocks.Persistence.Migrations
{
    [DbContext(typeof(FuaPayDbContext))]
    [Migration("20260731153404_AddPreGatewayOperations")]
    partial class AddPreGatewayOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FuaPay.Web.Modules.Access.Infrastructure.Persistence.AccessUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_access_users");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_access_users_email");

                    b.ToTable("users", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_users_display_name_not_empty", "length(btrim(display_name)) > 0");

                            t.HasCheckConstraint("ck_access_users_email_not_empty", "email IS NULL OR length(btrim(email)) > 0");

                            t.HasCheckConstraint("ck_access_users_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_access_users_last_seen_valid", "last_seen_at >= created_at");

                            t.HasCheckConstraint("ck_access_users_status_valid", "status IN (1, 2)");

                            t.HasCheckConstraint("ck_access_users_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Access.Infrastructure.Persistence.ExternalIdentityEntity", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider");

                    b.Property<string>("Tenant")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("tenant");

                    b.Property<string>("Subject")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Provider", "Tenant", "Subject")
                        .HasName("pk_access_external_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_access_external_identities_user");

                    b.ToTable("external_identities", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_external_identities_provider_not_empty", "length(btrim(provider)) > 0");

                            t.HasCheckConstraint("ck_access_external_identities_subject_not_empty", "length(btrim(subject)) > 0");

                            t.HasCheckConstraint("ck_access_external_identities_tenant_not_empty", "length(btrim(tenant)) > 0");

                            t.HasCheckConstraint("ck_access_external_identities_user_not_empty", "user_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Access.Infrastructure.Persistence.RoleAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedByProcessName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("granted_by_process_name");

                    b.Property<int>("GrantedByType")
                        .HasColumnType("integer")
                        .HasColumnName("granted_by_type");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByProcessName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("revoked_by_process_name");

                    b.Property<int?>("RevokedByType")
                        .HasColumnType("integer")
                        .HasColumnName("revoked_by_type");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_access_role_assignments");

                    b.HasIndex("GrantedByUserId")
                        .HasDatabaseName("ix_access_role_assignments_granted_by_user");

                    b.HasIndex("RevokedByUserId")
                        .HasDatabaseName("ix_access_role_assignments_revoked_by_user");

                    b.HasIndex("UserId", "GrantedAt")
                        .HasDatabaseName("ix_access_role_assignments_user_granted_at");

                    b.HasIndex("UserId", "Role")
                        .IsUnique()
                        .HasDatabaseName("uq_access_role_assignments_active_role")
                        .HasFilter("revoked_at IS NULL");

                    b.ToTable("role_assignments", "access", t =>
                        {
                            t.HasCheckConstraint("ck_access_role_assignments_granted_actor_valid", "(\n    granted_by_type = 1\n    AND granted_by_user_id IS NOT NULL\n    AND granted_by_process_name IS NULL\n)\nOR\n(\n    granted_by_type = 2\n    AND granted_by_user_id IS NULL\n    AND granted_by_process_name IS NOT NULL\n    AND length(btrim(granted_by_process_name)) > 0\n)");

                            t.HasCheckConstraint("ck_access_role_assignments_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_access_role_assignments_revoked_actor_valid", "(\n    revoked_at IS NULL\n    AND revoked_by_type IS NULL\n    AND revoked_by_user_id IS NULL\n    AND revoked_by_process_name IS NULL\n)\nOR\n(\n    revoked_at IS NOT NULL\n    AND revoked_at >= granted_at\n    AND\n    (\n        (\n            revoked_by_type = 1\n            AND revoked_by_user_id IS NOT NULL\n            AND revoked_by_process_name IS NULL\n        )\n        OR\n        (\n            revoked_by_type = 2\n            AND revoked_by_user_id IS NULL\n            AND revoked_by_process_name IS NOT NULL\n            AND length(btrim(revoked_by_process_name)) > 0\n        )\n    )\n)");

                            t.HasCheckConstraint("ck_access_role_assignments_role_valid", "role IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_access_role_assignments_user_not_empty", "user_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Audit.Infrastructure.Persistence.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("ActorProcessName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("actor_process_name");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_events_occurred_at");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_actor_user");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_entity");

                    b.ToTable("events", "audit", t =>
                        {
                            t.HasCheckConstraint("ck_audit_events_actor_consistent", "(actor_user_id IS NOT NULL AND actor_process_name IS NULL) OR (actor_user_id IS NULL AND actor_process_name IS NOT NULL)");

                            t.HasCheckConstraint("ck_audit_events_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_audit_events_text_not_blank", "length(btrim(action)) > 0 AND length(btrim(entity_type)) > 0 AND length(btrim(entity_id)) > 0 AND length(btrim(description)) > 0");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Credits.Infrastructure.Persistence.CreditAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("BalanceMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_minor_units");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_credits_accounts");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasDatabaseName("uq_credits_accounts_owner");

                    b.ToTable("accounts", "credits", t =>
                        {
                            t.HasCheckConstraint("ck_credits_accounts_balance_non_negative", "balance_minor_units >= 0");

                            t.HasCheckConstraint("ck_credits_accounts_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_credits_accounts_owner_not_empty", "owner_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_credits_accounts_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Credits.Infrastructure.Persistence.CreditMovementEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<long>("AmountMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor_units");

                    b.Property<long>("BalanceAfterMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after_minor_units");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer")
                        .HasColumnName("movement_type");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<long>("Sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("pk_credits_movements");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("uq_credits_movements_operation");

                    b.HasIndex("AccountId", "RecordedAt")
                        .HasDatabaseName("ix_credits_movements_account_recorded_at");

                    b.HasIndex("AccountId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("uq_credits_movements_account_sequence");

                    b.ToTable("movements", "credits", t =>
                        {
                            t.HasCheckConstraint("ck_credits_movements_account_not_empty", "account_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_credits_movements_amount_positive", "amount_minor_units > 0");

                            t.HasCheckConstraint("ck_credits_movements_balance_non_negative", "balance_after_minor_units >= 0");

                            t.HasCheckConstraint("ck_credits_movements_description_not_empty", "length(btrim(description)) > 0");

                            t.HasCheckConstraint("ck_credits_movements_operation_not_empty", "operation_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_credits_movements_sequence_positive", "sequence > 0");

                            t.HasCheckConstraint("ck_credits_movements_type_valid", "movement_type IN (1, 2)");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Jobs.Infrastructure.Persistence.JobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("CustomerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("job_number");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer")
                        .HasColumnName("payment_status");

                    b.Property<long>("PriceMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("price_minor_units");

                    b.Property<DateTimeOffset?>("ProductionStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("production_started_at");

                    b.Property<int>("ProductionStatus")
                        .HasColumnType("integer")
                        .HasColumnName("production_status");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<DateTimeOffset?>("ReadyForPickupAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ready_for_pickup_at");

                    b.Property<int>("ServiceType")
                        .HasColumnType("integer")
                        .HasColumnName("service_type");

                    b.Property<Guid>("ServiceUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_unit_id");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at");

                    b.Property<Guid?>("SettlementReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_reference_id");

                    b.Property<int?>("SettlementType")
                        .HasColumnType("integer")
                        .HasColumnName("settlement_type");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_jobs_jobs");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("uq_jobs_jobs_number");

                    b.HasIndex("CreatedByUserId", "CreatedAt")
                        .HasDatabaseName("ix_jobs_jobs_created_by_created_at");

                    b.HasIndex("CustomerUserId", "CreatedAt")
                        .HasDatabaseName("ix_jobs_jobs_customer_created_at");

                    b.HasIndex("ProductionStatus", "PaymentStatus")
                        .HasDatabaseName("ix_jobs_jobs_production_payment_status");

                    b.HasIndex("ServiceUnitId", "CreatedAt")
                        .HasDatabaseName("ix_jobs_jobs_service_unit_created_at");

                    b.HasIndex("SettlementType", "SettlementReferenceId")
                        .IsUnique()
                        .HasDatabaseName("uq_jobs_jobs_settlement_reference")
                        .HasFilter("settlement_type IS NOT NULL AND settlement_reference_id IS NOT NULL");

                    b.ToTable("jobs", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_jobs_jobs_created_by_not_empty", "created_by_user_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_jobs_jobs_customer_not_empty", "customer_user_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_jobs_jobs_description_not_empty", "length(btrim(description)) > 0");

                            t.HasCheckConstraint("ck_jobs_jobs_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_jobs_jobs_lifecycle_consistent", "(\n    production_status = 1\n    AND published_at IS NULL\n    AND production_started_at IS NULL\n    AND ready_for_pickup_at IS NULL\n    AND completed_at IS NULL\n    AND cancelled_at IS NULL\n)\nOR\n(\n    production_status = 2\n    AND published_at IS NOT NULL\n    AND production_started_at IS NULL\n    AND ready_for_pickup_at IS NULL\n    AND completed_at IS NULL\n    AND cancelled_at IS NULL\n)\nOR\n(\n    production_status = 3\n    AND published_at IS NOT NULL\n    AND production_started_at IS NOT NULL\n    AND ready_for_pickup_at IS NULL\n    AND completed_at IS NULL\n    AND cancelled_at IS NULL\n)\nOR\n(\n    production_status = 4\n    AND published_at IS NOT NULL\n    AND production_started_at IS NOT NULL\n    AND ready_for_pickup_at IS NOT NULL\n    AND completed_at IS NULL\n    AND cancelled_at IS NULL\n)\nOR\n(\n    production_status = 5\n    AND published_at IS NOT NULL\n    AND production_started_at IS NOT NULL\n    AND ready_for_pickup_at IS NOT NULL\n    AND completed_at IS NOT NULL\n    AND cancelled_at IS NULL\n)\nOR\n(\n    production_status = 6\n    AND production_started_at IS NULL\n    AND ready_for_pickup_at IS NULL\n    AND completed_at IS NULL\n    AND cancelled_at IS NOT NULL\n)");

                            t.HasCheckConstraint("ck_jobs_jobs_number_valid", "job_number ~ '^[A-Z0-9]{2,8}-[0-9]{4}-[0-9]{6}$'");

                            t.HasCheckConstraint("ck_jobs_jobs_paid_before_production", "(\n    production_status NOT IN (3, 4, 5)\n    OR payment_status = 2\n)\nAND\n(\n    production_status <> 6\n    OR payment_status = 1\n)");

                            t.HasCheckConstraint("ck_jobs_jobs_payment_status_valid", "payment_status IN (1, 2)");

                            t.HasCheckConstraint("ck_jobs_jobs_price_positive", "price_minor_units > 0");

                            t.HasCheckConstraint("ck_jobs_jobs_production_status_valid", "production_status IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("ck_jobs_jobs_service_type_valid", "service_type IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_jobs_jobs_service_unit_not_empty", "service_unit_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_jobs_jobs_settlement_consistent", "(\n    payment_status = 1\n    AND settlement_type IS NULL\n    AND settlement_reference_id IS NULL\n    AND settled_at IS NULL\n)\nOR\n(\n    payment_status = 2\n    AND settlement_type IN (1, 2)\n    AND settlement_reference_id IS NOT NULL\n    AND settlement_reference_id <>\n        '00000000-0000-0000-0000-000000000000'::uuid\n    AND settled_at IS NOT NULL\n    AND published_at IS NOT NULL\n    AND settled_at >= published_at\n)");

                            t.HasCheckConstraint("ck_jobs_jobs_timestamps_ordered", "(published_at IS NULL OR published_at >= created_at)\nAND\n(\n    settled_at IS NULL\n    OR\n    (\n        published_at IS NOT NULL\n        AND settled_at >= published_at\n    )\n)\nAND\n(\n    production_started_at IS NULL\n    OR\n    (\n        settled_at IS NOT NULL\n        AND production_started_at >= settled_at\n    )\n)\nAND\n(\n    ready_for_pickup_at IS NULL\n    OR\n    (\n        production_started_at IS NOT NULL\n        AND ready_for_pickup_at >= production_started_at\n    )\n)\nAND\n(\n    completed_at IS NULL\n    OR\n    (\n        ready_for_pickup_at IS NOT NULL\n        AND completed_at >= ready_for_pickup_at\n    )\n)\nAND\n(\n    cancelled_at IS NULL\n    OR cancelled_at >=\n        COALESCE(published_at, created_at)\n)");

                            t.HasCheckConstraint("ck_jobs_jobs_title_not_empty", "length(btrim(title)) > 0");

                            t.HasCheckConstraint("ck_jobs_jobs_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Jobs.Infrastructure.Persistence.JobNumberSequenceEntity", b =>
                {
                    b.Property<Guid>("ServiceUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_unit_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<int>("LastValue")
                        .HasColumnType("integer")
                        .HasColumnName("last_value");

                    b.HasKey("ServiceUnitId", "Year")
                        .HasName("pk_jobs_job_number_sequences");

                    b.ToTable("job_number_sequences", "jobs", t =>
                        {
                            t.HasCheckConstraint("ck_jobs_number_sequences_unit_not_empty", "service_unit_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_jobs_number_sequences_value_valid", "last_value BETWEEN 1 AND 999999");

                            t.HasCheckConstraint("ck_jobs_number_sequences_year_valid", "year BETWEEN 2000 AND 9999");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Notifications.Infrastructure.Persistence.NotificationOutboxEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("last_error");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications_outbox");

                    b.HasIndex("RecipientUserId", "CreatedAt")
                        .HasDatabaseName("ix_notifications_outbox_recipient_created");

                    b.HasIndex("SentAt", "CreatedAt")
                        .HasDatabaseName("ix_notifications_outbox_pending");

                    b.ToTable("outbox", "notifications", t =>
                        {
                            t.HasCheckConstraint("ck_notifications_outbox_attempt_count_nonnegative", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_notifications_outbox_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_notifications_outbox_recipient_not_empty", "recipient_user_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Payments.Infrastructure.Persistence.PaymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountMinorUnits")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_minor_units");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_user_id");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<int>("Provider")
                        .HasColumnType("integer")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderReference")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("provider_reference");

                    b.Property<int>("PurposeType")
                        .HasColumnType("integer")
                        .HasColumnName("purpose_type");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_payments_payments");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("uq_payments_open_job")
                        .HasFilter("job_id IS NOT NULL AND status IN (1, 2, 3)");

                    b.HasIndex("CustomerUserId", "CreatedAt")
                        .HasDatabaseName("ix_payments_customer_created_at");

                    b.HasIndex("Provider", "ProviderReference")
                        .IsUnique()
                        .HasDatabaseName("uq_payments_provider_reference")
                        .HasFilter("provider_reference IS NOT NULL");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_payments_status_created_at");

                    b.ToTable("payments", "payments", t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount_positive", "amount_minor_units > 0");

                            t.HasCheckConstraint("ck_payments_completion_consistent", "(status IN (1, 2) AND completed_at IS NULL) OR (status IN (3, 4, 5, 6) AND completed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_payments_customer_not_empty", "customer_user_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_payments_failure_consistent", "(status = 4 AND failure_reason IS NOT NULL AND length(btrim(failure_reason)) > 0) OR (status <> 4 AND failure_reason IS NULL)");

                            t.HasCheckConstraint("ck_payments_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_payments_provider_reference_consistent", "(status = 1 AND provider_reference IS NULL) OR (status <> 1 AND provider_reference IS NOT NULL AND length(btrim(provider_reference)) > 0)");

                            t.HasCheckConstraint("ck_payments_provider_valid", "provider IN (1, 2)");

                            t.HasCheckConstraint("ck_payments_purpose_consistent", "(purpose_type = 1 AND job_id IS NULL) OR (purpose_type = 2 AND job_id IS NOT NULL AND job_id <> '00000000-0000-0000-0000-000000000000'::uuid)");

                            t.HasCheckConstraint("ck_payments_purpose_valid", "purpose_type IN (1, 2)");

                            t.HasCheckConstraint("ck_payments_status_valid", "status IN (1, 2, 3, 4, 5, 6)");

                            t.HasCheckConstraint("ck_payments_timestamps_ordered", "updated_at >= created_at AND (completed_at IS NULL OR completed_at >= created_at)");

                            t.HasCheckConstraint("ck_payments_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.ServiceUnits.Infrastructure.Persistence.RequesterServiceUnitAssignmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedByProcessName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("granted_by_process_name");

                    b.Property<int>("GrantedByType")
                        .HasColumnType("integer")
                        .HasColumnName("granted_by_type");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedByProcessName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("revoked_by_process_name");

                    b.Property<int?>("RevokedByType")
                        .HasColumnType("integer")
                        .HasColumnName("revoked_by_type");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("revoked_by_user_id");

                    b.Property<Guid>("ServiceUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_unit_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_service_units_requester_assignments");

                    b.HasIndex("ServiceUnitId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_service_units_requester_assignments_active")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex("UserId", "GrantedAt")
                        .HasDatabaseName("ix_service_units_assignments_user_granted_at");

                    b.ToTable("requester_assignments", "service_units", t =>
                        {
                            t.HasCheckConstraint("ck_service_units_assignments_granted_actor_valid", "(\n    granted_by_type = 1\n    AND granted_by_user_id IS NOT NULL\n    AND granted_by_process_name IS NULL\n)\nOR\n(\n    granted_by_type = 2\n    AND granted_by_user_id IS NULL\n    AND granted_by_process_name IS NOT NULL\n    AND length(btrim(granted_by_process_name)) > 0\n)");

                            t.HasCheckConstraint("ck_service_units_assignments_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_service_units_assignments_revoked_actor_valid", "(\n    revoked_at IS NULL\n    AND revoked_by_type IS NULL\n    AND revoked_by_user_id IS NULL\n    AND revoked_by_process_name IS NULL\n)\nOR\n(\n    revoked_at IS NOT NULL\n    AND revoked_at >= granted_at\n    AND\n    ((\n    revoked_by_type = 1\n    AND revoked_by_user_id IS NOT NULL\n    AND revoked_by_process_name IS NULL\n)\nOR\n(\n    revoked_by_type = 2\n    AND revoked_by_user_id IS NULL\n    AND revoked_by_process_name IS NOT NULL\n    AND length(btrim(revoked_by_process_name)) > 0\n)    )\n)");

                            t.HasCheckConstraint("ck_service_units_assignments_unit_not_empty", "service_unit_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_service_units_assignments_user_not_empty", "user_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_service_units_assignments_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.ServiceUnits.Infrastructure.Persistence.ServiceUnitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByProcessName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("created_by_process_name");

                    b.Property<int>("CreatedByType")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_type");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTimeOffset?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<string>("DeactivatedByProcessName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("deactivated_by_process_name");

                    b.Property<int?>("DeactivatedByType")
                        .HasColumnType("integer")
                        .HasColumnName("deactivated_by_type");

                    b.Property<Guid?>("DeactivatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("deactivated_by_user_id");

                    b.Property<int>("DefaultServiceType")
                        .HasColumnType("integer")
                        .HasColumnName("default_service_type");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("display_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_service_units_units");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_service_units_units_code");

                    b.HasIndex("Status", "DisplayName")
                        .HasDatabaseName("ix_service_units_units_status_name");

                    b.ToTable("units", "service_units", t =>
                        {
                            t.HasCheckConstraint("ck_service_units_units_code_valid", "code ~ '^[A-Z0-9]{2,8}$'");

                            t.HasCheckConstraint("ck_service_units_units_created_actor_valid", "(\n    created_by_type = 1\n    AND created_by_user_id IS NOT NULL\n    AND created_by_process_name IS NULL\n)\nOR\n(\n    created_by_type = 2\n    AND created_by_user_id IS NULL\n    AND created_by_process_name IS NOT NULL\n    AND length(btrim(created_by_process_name)) > 0\n)");

                            t.HasCheckConstraint("ck_service_units_units_deactivated_actor_valid", "(\n    status = 1\n    AND deactivated_at IS NULL\n    AND deactivated_by_type IS NULL\n    AND deactivated_by_user_id IS NULL\n    AND deactivated_by_process_name IS NULL\n)\nOR\n(\n    status = 2\n    AND deactivated_at IS NOT NULL\n    AND deactivated_at >= created_at\n    AND\n    ((\n    deactivated_by_type = 1\n    AND deactivated_by_user_id IS NOT NULL\n    AND deactivated_by_process_name IS NULL\n)\nOR\n(\n    deactivated_by_type = 2\n    AND deactivated_by_user_id IS NULL\n    AND deactivated_by_process_name IS NOT NULL\n    AND length(btrim(deactivated_by_process_name)) > 0\n)    )\n)");

                            t.HasCheckConstraint("ck_service_units_units_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_service_units_units_name_not_blank", "length(btrim(display_name)) > 0");

                            t.HasCheckConstraint("ck_service_units_units_service_type_valid", "default_service_type IN (1, 2, 3)");

                            t.HasCheckConstraint("ck_service_units_units_status_valid", "status IN (1, 2)");

                            t.HasCheckConstraint("ck_service_units_units_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Access.Infrastructure.Persistence.ExternalIdentityEntity", b =>
                {
                    b.HasOne("FuaPay.Web.Modules.Access.Infrastructure.Persistence.AccessUserEntity", "User")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_external_identities_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Access.Infrastructure.Persistence.RoleAssignmentEntity", b =>
                {
                    b.HasOne("FuaPay.Web.Modules.Access.Infrastructure.Persistence.AccessUserEntity", null)
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_access_role_assignments_granted_by_user");

                    b.HasOne("FuaPay.Web.Modules.Access.Infrastructure.Persistence.AccessUserEntity", null)
                        .WithMany()
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_access_role_assignments_revoked_by_user");

                    b.HasOne("FuaPay.Web.Modules.Access.Infrastructure.Persistence.AccessUserEntity", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_access_role_assignments_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Credits.Infrastructure.Persistence.CreditMovementEntity", b =>
                {
                    b.HasOne("FuaPay.Web.Modules.Credits.Infrastructure.Persistence.CreditAccountEntity", "Account")
                        .WithMany("Movements")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("FuaPay.Web.Modules.ServiceUnits.Infrastructure.Persistence.RequesterServiceUnitAssignmentEntity", b =>
                {
                    b.HasOne("FuaPay.Web.Modules.ServiceUnits.Infrastructure.Persistence.ServiceUnitEntity", "ServiceUnit")
                        .WithMany("RequesterAssignments")
                        .HasForeignKey("ServiceUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_service_units_assignments_unit");

                    b.Navigation("ServiceUnit");
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Access.Infrastructure.Persistence.AccessUserEntity", b =>
                {
                    b.Navigation("ExternalIdentities");

                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("FuaPay.Web.Modules.Credits.Infrastructure.Persistence.CreditAccountEntity", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("FuaPay.Web.Modules.ServiceUnits.Infrastructure.Persistence.ServiceUnitEntity", b =>
                {
                    b.Navigation("RequesterAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
